---
# - name: install required software
#   yum:
#     name: "{{ item }}"
#     state: installed
#   with_items:
#     - rsnapshot
#     - cron

- name: create backup directories
  file:
    dest: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items:
    - /var/backup/{{ ansible_hostname }}
    - /var/backup/{{ ansible_hostname }}/.sync
  tags:
    - directories

- name: install rsnapshot config
  template:
    src: "etc/rsnapshot.j2"
    dest: "/etc/rsnapshot.conf"
  tags:
    - rsnapshot

- name: setup cron
  cron:
    user: "root"
    job: "{{ item.job }}"
    name: "snapshot-{{ item.name }}"
    weekday: "{{ item.weekday }}"
    minute: "00"
    hour: "{{ item.hour }}"
    dom: "{{ item.dom|default('*') }}"
  with_items:
    - { job: '{{ snapshot_daily }}', name: 'daily', weekday: '*', hour: '04' }
    - { job: '{{ snapshot_weekly }}', name: 'weekly', weekday: '00', hour: '02' }
    - { job: '{{ snapshot_monthly }}', name: 'monthly', weekday: '*', hour: '00', dom: '01' }
  tags:
    - cron

- name: install excludes
  copy:
    dest: "/var/backup/{{ ansible_hostname }}/exclude_file.txt"
    src: "var/backup/hostname/exclude_file.txt"
    mode: 0775
  tags:
    - config
